name: Adjust a load balancer

on:
  workflow_dispatch:
    inputs:
      port_context:
        required: true
        description: Information sent from Port
      securityGroup:
        required: true
        description: Security group

jobs:
  adjust_load_balancer:
    runs-on: ubuntu-latest
    steps:
      - name: Log starting of action
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Beginning the process of adjusting ${{ fromJson(inputs.port_context).entity.title }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Overwrite terraform.tfvars
        run: |
          # overwrite
          sed -i 's/^security_group_id = .*/security_group_id = "${{ inputs.security_group.identifier }}"/' infra/terraform.tfvars || echo "security_group_id = \"${{ inputs.security_group.identifier }}\"" >> infra/terraform.tfvars
      - name: Another log of action
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Adding ${{ inputs.securityGroup }} as a security group for ${{ fromJson(inputs.port_context).entity.title }}
