name: On Push Port Run

on: push

env:
  FRONTEND_DIR: frontend_service

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v2
      with:
        repository: oconnorac/frontend_service
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.FRONTEND_DIR }}

    - name: Hello World
      run: ll #& sh ${{ env.FRONTEND_DIR }}/porter.sh
      shell: sh
